"""empty message

Revision ID: 029b94fefd22
Revises: d450e82c9885
Create Date: 2018-12-21 10:37:19.768301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029b94fefd22'
down_revision = 'd450e82c9885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_models',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('dataset_var', sa.String(length=128), nullable=False),
    sa.Column('dataset_path', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset_models')
    # ### end Alembic commands ###
