"""empty message

Revision ID: 0d4935816085
Revises: 1a1ee148b503
Create Date: 2018-10-23 10:56:26.983771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4935816085'
down_revision = '1a1ee148b503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_models', sa.Column('trained_path', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_models', 'trained_path')
    # ### end Alembic commands ###
