"""empty message

Revision ID: 1a1ee148b503
Revises: a3b9cf9238ab
Create Date: 2018-10-16 17:53:42.679189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a1ee148b503'
down_revision = 'a3b9cf9238ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_models', sa.Column('test_dataset_id', sa.Integer(), nullable=False))
    op.add_column('task_models', sa.Column('test_dataset_path', sa.String(length=256), nullable=True))
    op.add_column('task_models', sa.Column('test_dataset_var', sa.String(length=128), nullable=False))
    op.add_column('task_models', sa.Column('train_dataset_id', sa.Integer(), nullable=False))
    op.add_column('task_models', sa.Column('train_dataset_path', sa.String(length=256), nullable=True))
    op.add_column('task_models', sa.Column('train_dataset_var', sa.String(length=128), nullable=False))
    op.drop_column('task_models', 'test_data_id')
    op.drop_column('task_models', 'train_data_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_models', sa.Column('train_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('task_models', sa.Column('test_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('task_models', 'train_dataset_var')
    op.drop_column('task_models', 'train_dataset_path')
    op.drop_column('task_models', 'train_dataset_id')
    op.drop_column('task_models', 'test_dataset_var')
    op.drop_column('task_models', 'test_dataset_path')
    op.drop_column('task_models', 'test_dataset_id')
    # ### end Alembic commands ###
