"""empty message

Revision ID: 5eeb088246e8
Revises: 49e81816e446
Create Date: 2018-12-24 11:03:02.105571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eeb088246e8'
down_revision = '49e81816e446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result_models', sa.Column('model_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result_models', 'model_id')
    # ### end Alembic commands ###
