"""empty message

Revision ID: a3b9cf9238ab
Revises: 
Create Date: 2018-10-12 11:11:32.998230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b9cf9238ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ds_labels',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('task_models',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('train_data_id', sa.Integer(), nullable=False),
    sa.Column('test_data_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=128), nullable=True),
    sa.Column('loss', sa.String(length=32), nullable=True),
    sa.Column('accuracy', sa.String(length=32), nullable=True),
    sa.Column('plt_path', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('train_models',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('frame', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('define_path', sa.String(length=256), nullable=False),
    sa.Column('weight_path', sa.String(length=256), nullable=False),
    sa.Column('width', sa.String(length=32), nullable=False),
    sa.Column('height', sa.String(length=32), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ds_users',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('permission', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ds_users_email'), 'ds_users', ['email'], unique=True)
    op.create_table('ds_collections',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.Column('parameter_1', sa.String(length=32), nullable=True),
    sa.Column('parameter_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ds_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_label',
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['ds_collections.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['ds_labels.id'], )
    )
    op.create_table('ds_versions',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['ds_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ds_images',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('site', sa.String(length=128), nullable=False),
    sa.Column('label_path', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('structured_path', sa.String(length=128), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['ds_collections.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['ds_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ds_images_md5'), 'ds_images', ['md5'], unique=False)
    op.create_table('version_label',
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['ds_labels.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['ds_versions.id'], )
    )
    op.create_table('label_image',
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['ds_images.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['ds_labels.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('label_image')
    op.drop_table('version_label')
    op.drop_index(op.f('ix_ds_images_md5'), table_name='ds_images')
    op.drop_table('ds_images')
    op.drop_table('ds_versions')
    op.drop_table('collection_label')
    op.drop_table('ds_collections')
    op.drop_index(op.f('ix_ds_users_email'), table_name='ds_users')
    op.drop_table('ds_users')
    op.drop_table('train_models')
    op.drop_table('task_models')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('ds_labels')
    # ### end Alembic commands ###
