"""empty message

Revision ID: d450e82c9885
Revises: 0d4935816085
Create Date: 2018-10-23 11:31:35.447541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd450e82c9885'
down_revision = '0d4935816085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_models', 'loss')
    op.drop_column('task_models', 'accuracy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_models', sa.Column('accuracy', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('task_models', sa.Column('loss', mysql.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
